"""add user role

Revision ID: 55657a7d8ec3
Revises: d103ffe91cfd
Create Date: 2026-10-08 14:54:20.888922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55657a7d8ec3'
down_revision: Union[str, Sequence[str], None] = 'd103ffe91cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column('role', sa.String(length=20), nullable=False, server_default='user')
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
