"""add car listing type and rental price

Revision ID: ecd9fdf1031b
Revises: 94bac7ae6b0b
Create Date: 2026-10-09 16:19:23.837122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd9fdf1031b'
down_revision: Union[str, Sequence[str], None] = '94bac7ae6b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cars",
        sa.Column(
            "listing_type",
            sa.String(length=10),
            nullable=False,
            server_default="both",
        ),
    )
    op.add_column('cars', sa.Column('rental_price_per_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'rental_price_per_day')
    op.drop_column('cars', 'listing_type')
    # ### end Alembic commands ###
